2021/04/08 11:14:23 - pre_loading_data - Using run configuration [Pentaho local]
2021/04/08 11:19:00 - load_plain - Using run configuration [Pentaho local]
2021/04/08 11:21:18 - load_link - Using run configuration [Pentaho local]
2021/04/08 11:21:35 - ti_main_entity 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:21:35 - ti_main_entity.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:21:35 - ti_main_entity 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:21:35 - ti_main_entity 2.0 - An error occurred executing SQL: 
2021/04/08 11:21:35 - ti_main_entity 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:21:35 - ti_main_entity 2.0 - (conn=7204) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - ti_main_entity 2.0 - 
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1772)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:236)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:21:35 - ti_main_entity 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7204) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1761)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	... 4 more
2021/04/08 11:21:35 - ti_main_entity 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
2021/04/08 11:21:35 - ti_main_entity 2.0 - 	... 6 more
2021/04/08 11:21:35 - ti_main_entity.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:21:35 - ti_main_entity.0 - An error occurred executing SQL: 
2021/04/08 11:21:35 - ti_main_entity.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:21:35 - ti_main_entity.0 - (conn=7202) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - ti_main_entity.0 - 
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1772)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:236)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:21:35 - ti_main_entity.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7202) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1761)
2021/04/08 11:21:35 - ti_main_entity.0 - 	... 4 more
2021/04/08 11:21:35 - ti_main_entity.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
2021/04/08 11:21:35 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
2021/04/08 11:21:35 - ti_main_entity.0 - 	... 6 more
2021/04/08 11:21:35 - 5.4.12_cvn_load_link_publication - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Errors detected!
2021/04/08 11:21:35 - grp 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:21:35 - grp 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:21:35 - grp 2.0 - Unable to get queryfields for SQL: 
2021/04/08 11:21:35 - grp 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:21:35 - grp 2.0 - 
2021/04/08 11:21:35 - grp 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:21:35 - grp 2.0 - 
2021/04/08 11:21:35 - grp 2.0 - (conn=7205) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - grp 2.0 - 
2021/04/08 11:21:35 - grp 2.0 - 
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2042)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1951)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1921)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1904)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.steps.groupby.GroupBy.processRow(GroupBy.java:114)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:21:35 - grp 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:21:35 - grp 2.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:21:35 - grp 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:21:35 - grp 2.0 - 
2021/04/08 11:21:35 - grp 2.0 - (conn=7205) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - grp 2.0 - 
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:21:35 - grp 2.0 - 	... 16 more
2021/04/08 11:21:35 - grp 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7205) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:21:35 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:21:35 - grp 2.0 - 	... 18 more
2021/04/08 11:21:35 - grp 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:21:35 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:21:35 - grp 2.0 - 	... 21 more
2021/04/08 11:21:35 - Merge join 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:21:35 - Merge join 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:21:35 - Merge join 2.0 - Unable to get queryfields for SQL: 
2021/04/08 11:21:35 - Merge join 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:21:35 - Merge join 2.0 - 
2021/04/08 11:21:35 - Merge join 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:21:35 - Merge join 2.0 - 
2021/04/08 11:21:35 - Merge join 2.0 - (conn=7207) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join 2.0 - 
2021/04/08 11:21:35 - Merge join 2.0 - 
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1716)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.mergejoin.MergeJoin.processRow(MergeJoin.java:99)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:21:35 - Merge join 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:21:35 - Merge join 2.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:21:35 - Merge join 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:21:35 - Merge join 2.0 - 
2021/04/08 11:21:35 - Merge join 2.0 - (conn=7207) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join 2.0 - 
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:21:35 - Merge join 2.0 - 	... 10 more
2021/04/08 11:21:35 - Merge join 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7207) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:21:35 - Merge join 2.0 - 	... 12 more
2021/04/08 11:21:35 - Merge join 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:21:35 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:21:35 - Merge join 2.0 - 	... 15 more
2021/04/08 11:21:35 - Merge join.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:21:35 - Merge join.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:21:35 - Merge join.0 - Unable to get queryfields for SQL: 
2021/04/08 11:21:35 - Merge join.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:21:35 - Merge join.0 - 
2021/04/08 11:21:35 - Merge join.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:21:35 - Merge join.0 - 
2021/04/08 11:21:35 - Merge join.0 - (conn=7206) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join.0 - 
2021/04/08 11:21:35 - Merge join.0 - 
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1716)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.steps.mergejoin.MergeJoin.processRow(MergeJoin.java:99)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:21:35 - Merge join.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:21:35 - Merge join.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:21:35 - Merge join.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:21:35 - Merge join.0 - 
2021/04/08 11:21:35 - Merge join.0 - (conn=7206) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join.0 - 
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:21:35 - Merge join.0 - 	... 11 more
2021/04/08 11:21:35 - Merge join.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7206) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:21:35 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:21:35 - Merge join.0 - 	... 13 more
2021/04/08 11:21:35 - Merge join.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:21:35 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:21:35 - Merge join.0 - 	... 16 more
2021/04/08 11:21:36 - 5.4.12_cvn_load_link_publication - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Errors detected!
2021/04/08 11:21:38 - abrt_entity_load_fail - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : ERROR: load PUBLICATION_LINK entity fail
2021/04/08 11:22:47 - finalize_succeeded - Using run configuration [Pentaho local]
2021/04/08 11:25:33 - load_plain_research_accreditation - Using run configuration [Pentaho local]
2021/04/08 11:25:33 - load_plain_research_accreditation - Running transformation using the Kettle execution engine
2021/04/08 11:25:37 - load_plain_project - Using run configuration [Pentaho local]
2021/04/08 11:25:37 - load_plain_project - Running transformation using the Kettle execution engine
2021/04/08 11:25:42 - load_plain_project_cvn - Using run configuration [Pentaho local]
2021/04/08 11:25:42 - load_plain_project_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:25:44 - load_plain_invoice - Using run configuration [Pentaho local]
2021/04/08 11:25:44 - load_plain_invoice - Running transformation using the Kettle execution engine
2021/04/08 11:25:47 - load_plain_publication_cvn - Using run configuration [Pentaho local]
2021/04/08 11:25:47 - load_plain_publication_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:25:49 - load_plain_patent - Using run configuration [Pentaho local]
2021/04/08 11:25:49 - load_plain_patent - Running transformation using the Kettle execution engine
2021/04/08 11:25:50 - load_plain_patent_cvn - Using run configuration [Pentaho local]
2021/04/08 11:25:50 - load_plain_patent_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:25:52 - load_plain_article - Using run configuration [Pentaho local]
2021/04/08 11:25:52 - load_plain_article - Running transformation using the Kettle execution engine
2021/04/08 11:25:56 - load_plain_book - Using run configuration [Pentaho local]
2021/04/08 11:25:56 - load_plain_book - Running transformation using the Kettle execution engine
2021/04/08 11:26:00 - load_plain_book_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:00 - load_plain_book_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:02 - load_plain_doctoral_thesis - Using run configuration [Pentaho local]
2021/04/08 11:26:02 - load_plain_doctoral_thesis - Running transformation using the Kettle execution engine
2021/04/08 11:26:05 - load_plain_doctoral_thesis_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:05 - load_plain_doctoral_thesis_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:07 - load_plain_master_thesis - Using run configuration [Pentaho local]
2021/04/08 11:26:07 - load_plain_master_thesis - Running transformation using the Kettle execution engine
2021/04/08 11:26:08 - load_plain_cv_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:08 - load_plain_cv_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:10 - load_plain_dossier - Using run configuration [Pentaho local]
2021/04/08 11:26:10 - load_plain_dossier - Running transformation using the Kettle execution engine
2021/04/08 11:26:14 - load_plain_researchGroup - Using run configuration [Pentaho local]
2021/04/08 11:26:14 - load_plain_researchGroup - Running transformation using the Kettle execution engine
2021/04/08 11:26:16 - load_plain_researchGroup_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:16 - load_plain_researchGroup_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:18 - load_plain_group - Using run configuration [Pentaho local]
2021/04/08 11:26:18 - load_plain_group - Running transformation using the Kettle execution engine
2021/04/08 11:26:24 - load_plain_university - Using run configuration [Pentaho local]
2021/04/08 11:26:24 - load_plain_university - Running transformation using the Kettle execution engine
2021/04/08 11:26:25 - load_plain_patent_asignee - Using run configuration [Pentaho local]
2021/04/08 11:26:25 - load_plain_patent_asignee - Running transformation using the Kettle execution engine
2021/04/08 11:26:26 - load_plain_patent_owner - Using run configuration [Pentaho local]
2021/04/08 11:26:26 - load_plain_patent_owner - Running transformation using the Kettle execution engine
2021/04/08 11:26:27 - load_plain_funding_organization_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:27 - load_plain_funding_organization_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:29 - load_plain_person - Using run configuration [Pentaho local]
2021/04/08 11:26:29 - load_plain_person - Running transformation using the Kettle execution engine
2021/04/08 11:26:46 - load_plain_person_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:46 - load_plain_person_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:48 - load_plain_conference - Using run configuration [Pentaho local]
2021/04/08 11:26:48 - load_plain_conference - Running transformation using the Kettle execution engine
2021/04/08 11:26:52 - load_plain_conference_cvn - Using run configuration [Pentaho local]
2021/04/08 11:26:52 - load_plain_conference_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:26:55 - load_plain_exhibit - Using run configuration [Pentaho local]
2021/04/08 11:26:55 - load_plain_exhibit - Running transformation using the Kettle execution engine
2021/04/08 11:26:59 - load_plain_internship - Using run configuration [Pentaho local]
2021/04/08 11:26:59 - load_plain_internship - Running transformation using the Kettle execution engine
2021/04/08 11:27:04 - load_plain_funding - Using run configuration [Pentaho local]
2021/04/08 11:27:04 - load_plain_funding - Running transformation using the Kettle execution engine
2021/04/08 11:27:05 - load_plain_funding_source - Using run configuration [Pentaho local]
2021/04/08 11:27:05 - load_plain_funding_source - Running transformation using the Kettle execution engine
2021/04/08 11:27:06 - load_plain_project_expense - Using run configuration [Pentaho local]
2021/04/08 11:27:06 - load_plain_project_expense - Running transformation using the Kettle execution engine
2021/04/08 11:27:10 - load_plain_patent_expense - Using run configuration [Pentaho local]
2021/04/08 11:27:10 - load_plain_patent_expense - Running transformation using the Kettle execution engine
2021/04/08 11:27:12 - load_plain_editor - Using run configuration [Pentaho local]
2021/04/08 11:27:12 - load_plain_editor - Running transformation using the Kettle execution engine
2021/04/08 11:27:14 - load_plain_member - Using run configuration [Pentaho local]
2021/04/08 11:27:14 - load_plain_member - Running transformation using the Kettle execution engine
2021/04/08 11:27:16 - load_plain_supervisor - Using run configuration [Pentaho local]
2021/04/08 11:27:16 - load_plain_supervisor - Running transformation using the Kettle execution engine
2021/04/08 11:27:19 - load_plain_researcher - Using run configuration [Pentaho local]
2021/04/08 11:27:19 - load_plain_researcher - Running transformation using the Kettle execution engine
2021/04/08 11:27:22 - load_plain_project_contract - Using run configuration [Pentaho local]
2021/04/08 11:27:22 - load_plain_project_contract - Running transformation using the Kettle execution engine
2021/04/08 11:27:26 - load_plain_employment_contract - Using run configuration [Pentaho local]
2021/04/08 11:27:26 - load_plain_employment_contract - Running transformation using the Kettle execution engine
2021/04/08 11:27:30 - load_plain_awarded_degree_cvn - Using run configuration [Pentaho local]
2021/04/08 11:27:30 - load_plain_awarded_degree_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:27:32 - load_plain_research_field - Using run configuration [Pentaho local]
2021/04/08 11:27:32 - load_plain_research_field - Running transformation using the Kettle execution engine
2021/04/08 11:27:34 - load_plain_keyword - Using run configuration [Pentaho local]
2021/04/08 11:27:34 - load_plain_keyword - Running transformation using the Kettle execution engine
2021/04/08 11:27:41 - load_plain_academic_degree - Using run configuration [Pentaho local]
2021/04/08 11:27:41 - load_plain_academic_degree - Running transformation using the Kettle execution engine
2021/04/08 11:27:43 - load_plain_funding_program_cvn - Using run configuration [Pentaho local]
2021/04/08 11:27:43 - load_plain_funding_program_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:27:58 - load_link_accreditation - Using run configuration [Pentaho local]
2021/04/08 11:27:58 - load_link_accreditation - Running transformation using the Kettle execution engine
2021/04/08 11:28:02 - load_link_project - Using run configuration [Pentaho local]
2021/04/08 11:28:02 - load_link_project - Running transformation using the Kettle execution engine
2021/04/08 11:28:07 - load_link_project_cvn - Using run configuration [Pentaho local]
2021/04/08 11:28:07 - load_link_project_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:28:11 - load_link_publication_cvn - Using run configuration [Pentaho local]
2021/04/08 11:28:11 - load_link_publication_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:28:11 - ti_main_entity.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:28:11 - ti_main_entity.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:28:11 - ti_main_entity.0 - An error occurred executing SQL: 
2021/04/08 11:28:11 - ti_main_entity.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:28:11 - ti_main_entity.0 - (conn=7467) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - ti_main_entity.0 - 
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1772)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:236)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:28:11 - ti_main_entity.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7467) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1761)
2021/04/08 11:28:11 - ti_main_entity.0 - 	... 4 more
2021/04/08 11:28:11 - ti_main_entity.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
2021/04/08 11:28:11 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
2021/04/08 11:28:11 - ti_main_entity.0 - 	... 6 more
2021/04/08 11:28:11 - 5.4.12_cvn_load_link_publication - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Errors detected!
2021/04/08 11:28:11 - ti_main_entity 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:28:11 - ti_main_entity 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:28:11 - ti_main_entity 2.0 - An error occurred executing SQL: 
2021/04/08 11:28:11 - ti_main_entity 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:28:11 - ti_main_entity 2.0 - (conn=7468) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - ti_main_entity 2.0 - 
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1772)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:236)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:28:11 - ti_main_entity 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7468) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1761)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	... 4 more
2021/04/08 11:28:11 - ti_main_entity 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
2021/04/08 11:28:11 - ti_main_entity 2.0 - 	... 6 more
2021/04/08 11:28:11 - grp 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:28:11 - grp 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:28:11 - grp 2.0 - Unable to get queryfields for SQL: 
2021/04/08 11:28:11 - grp 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:28:11 - grp 2.0 - 
2021/04/08 11:28:11 - grp 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:28:11 - grp 2.0 - 
2021/04/08 11:28:11 - grp 2.0 - (conn=7470) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - grp 2.0 - 
2021/04/08 11:28:11 - grp 2.0 - 
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2042)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1951)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1921)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1904)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.steps.groupby.GroupBy.processRow(GroupBy.java:114)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:28:11 - grp 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:28:11 - grp 2.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:28:11 - grp 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:28:11 - grp 2.0 - 
2021/04/08 11:28:11 - grp 2.0 - (conn=7470) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - grp 2.0 - 
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:28:11 - grp 2.0 - 	... 16 more
2021/04/08 11:28:11 - grp 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7470) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:28:11 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:28:11 - grp 2.0 - 	... 18 more
2021/04/08 11:28:11 - grp 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:28:11 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:28:11 - grp 2.0 - 	... 21 more
2021/04/08 11:28:11 - Merge join.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:28:11 - Merge join.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:28:11 - Merge join.0 - Unable to get queryfields for SQL: 
2021/04/08 11:28:11 - Merge join.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:28:11 - Merge join.0 - 
2021/04/08 11:28:11 - Merge join.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:28:11 - Merge join.0 - 
2021/04/08 11:28:11 - Merge join.0 - (conn=7471) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join.0 - 
2021/04/08 11:28:11 - Merge join.0 - 
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1716)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.steps.mergejoin.MergeJoin.processRow(MergeJoin.java:99)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:28:11 - Merge join.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:28:11 - Merge join.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:28:11 - Merge join.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:28:11 - Merge join.0 - 
2021/04/08 11:28:11 - Merge join.0 - (conn=7471) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join.0 - 
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:28:11 - Merge join.0 - 	... 11 more
2021/04/08 11:28:11 - Merge join.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7471) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:28:11 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:28:11 - Merge join.0 - 	... 13 more
2021/04/08 11:28:11 - Merge join.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:28:11 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:28:11 - Merge join.0 - 	... 16 more
2021/04/08 11:28:11 - Merge join 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:28:11 - Merge join 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:28:11 - Merge join 2.0 - Unable to get queryfields for SQL: 
2021/04/08 11:28:11 - Merge join 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:28:11 - Merge join 2.0 - 
2021/04/08 11:28:11 - Merge join 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:28:11 - Merge join 2.0 - 
2021/04/08 11:28:11 - Merge join 2.0 - (conn=7472) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join 2.0 - 
2021/04/08 11:28:11 - Merge join 2.0 - 
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1716)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.mergejoin.MergeJoin.processRow(MergeJoin.java:99)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:28:11 - Merge join 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:28:11 - Merge join 2.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:28:11 - Merge join 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:28:11 - Merge join 2.0 - 
2021/04/08 11:28:11 - Merge join 2.0 - (conn=7472) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join 2.0 - 
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:28:11 - Merge join 2.0 - 	... 10 more
2021/04/08 11:28:11 - Merge join 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7472) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:28:11 - Merge join 2.0 - 	... 12 more
2021/04/08 11:28:11 - Merge join 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:28:11 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:28:11 - Merge join 2.0 - 	... 15 more
2021/04/08 11:28:12 - 5.4.12_cvn_load_link_publication - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Errors detected!
2021/04/08 11:28:13 - control_error - Using run configuration [Pentaho local]
2021/04/08 11:28:13 - control_error - Running transformation using the Kettle execution engine
2021/04/08 11:28:17 - load_link_dossier - Using run configuration [Pentaho local]
2021/04/08 11:28:17 - load_link_dossier - Running transformation using the Kettle execution engine
2021/04/08 11:28:21 - load_link_research_group - Using run configuration [Pentaho local]
2021/04/08 11:28:21 - load_link_research_group - Running transformation using the Kettle execution engine
2021/04/08 11:28:25 - load_link_university - Using run configuration [Pentaho local]
2021/04/08 11:28:25 - load_link_university - Running transformation using the Kettle execution engine
2021/04/08 11:28:29 - load_link_funding_org_cvn - Using run configuration [Pentaho local]
2021/04/08 11:28:29 - load_link_funding_org_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:28:33 - load_link_person_cvn - Using run configuration [Pentaho local]
2021/04/08 11:28:33 - load_link_person_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:28:37 - load_link_conference - Using run configuration [Pentaho local]
2021/04/08 11:28:37 - load_link_conference - Running transformation using the Kettle execution engine
2021/04/08 11:28:41 - load_link_conference_cvn - Using run configuration [Pentaho local]
2021/04/08 11:28:41 - load_link_conference_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:28:45 - load_link_exhibit - Using run configuration [Pentaho local]
2021/04/08 11:28:45 - load_link_exhibit - Running transformation using the Kettle execution engine
2021/04/08 11:28:49 - load_link_internship - Using run configuration [Pentaho local]
2021/04/08 11:28:49 - load_link_internship - Running transformation using the Kettle execution engine
2021/04/08 11:28:53 - load_link_editor - Using run configuration [Pentaho local]
2021/04/08 11:28:53 - load_link_editor - Running transformation using the Kettle execution engine
2021/04/08 11:28:57 - load_link_member - Using run configuration [Pentaho local]
2021/04/08 11:28:57 - load_link_member - Running transformation using the Kettle execution engine
2021/04/08 11:29:01 - load_link_supervisor - Using run configuration [Pentaho local]
2021/04/08 11:29:01 - load_link_supervisor - Running transformation using the Kettle execution engine
2021/04/08 11:29:05 - load_link_researcher - Using run configuration [Pentaho local]
2021/04/08 11:29:05 - load_link_researcher - Running transformation using the Kettle execution engine
2021/04/08 11:29:09 - load_link_project_contract - Using run configuration [Pentaho local]
2021/04/08 11:29:09 - load_link_project_contract - Running transformation using the Kettle execution engine
2021/04/08 11:29:13 - load_link_employment_contract - Using run configuration [Pentaho local]
2021/04/08 11:29:13 - load_link_employment_contract - Running transformation using the Kettle execution engine
2021/04/08 11:29:17 - load_link_awarded_degree_cvn - Using run configuration [Pentaho local]
2021/04/08 11:29:17 - load_link_awarded_degree_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:29:21 - load_link_funding_program_cvn - Using run configuration [Pentaho local]
2021/04/08 11:29:21 - load_link_funding_program_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:30:12 - load_link_publication_cvn - Using run configuration [Pentaho local]
2021/04/08 11:30:12 - load_link_publication_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:30:12 - ti_main_entity.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:30:12 - ti_main_entity.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:30:12 - ti_main_entity.0 - An error occurred executing SQL: 
2021/04/08 11:30:12 - ti_main_entity.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:30:12 - ti_main_entity.0 - (conn=7507) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - ti_main_entity.0 - 
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1772)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:236)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:30:12 - ti_main_entity.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7507) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1761)
2021/04/08 11:30:12 - ti_main_entity.0 - 	... 4 more
2021/04/08 11:30:12 - ti_main_entity.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
2021/04/08 11:30:12 - ti_main_entity.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
2021/04/08 11:30:12 - ti_main_entity.0 - 	... 6 more
2021/04/08 11:30:12 - ti_main_entity 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:30:12 - ti_main_entity 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:30:12 - ti_main_entity 2.0 - An error occurred executing SQL: 
2021/04/08 11:30:12 - ti_main_entity 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:30:12 - ti_main_entity 2.0 - (conn=7505) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - ti_main_entity 2.0 - 
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1772)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:236)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:30:12 - ti_main_entity 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7505) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.pentaho.di.core.database.Database.openQuery(Database.java:1761)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	... 4 more
2021/04/08 11:30:12 - ti_main_entity 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
2021/04/08 11:30:12 - ti_main_entity 2.0 - 	... 6 more
2021/04/08 11:30:12 - 5.4.12_cvn_load_link_publication - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Errors detected!
2021/04/08 11:30:12 - grp 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:30:12 - grp 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:30:12 - grp 2.0 - Unable to get queryfields for SQL: 
2021/04/08 11:30:12 - grp 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:30:12 - grp 2.0 - 
2021/04/08 11:30:12 - grp 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:30:12 - grp 2.0 - 
2021/04/08 11:30:12 - grp 2.0 - (conn=7508) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - grp 2.0 - 
2021/04/08 11:30:12 - grp 2.0 - 
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2042)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1951)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1921)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1904)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.steps.groupby.GroupBy.processRow(GroupBy.java:114)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:30:12 - grp 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:30:12 - grp 2.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:30:12 - grp 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:30:12 - grp 2.0 - 
2021/04/08 11:30:12 - grp 2.0 - (conn=7508) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - grp 2.0 - 
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:30:12 - grp 2.0 - 	... 16 more
2021/04/08 11:30:12 - grp 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7508) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:30:12 - grp 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:30:12 - grp 2.0 - 	... 18 more
2021/04/08 11:30:12 - grp 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:30:12 - grp 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:30:12 - grp 2.0 - 	... 21 more
2021/04/08 11:30:12 - Merge join.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:30:12 - Merge join.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:30:12 - Merge join.0 - Unable to get queryfields for SQL: 
2021/04/08 11:30:12 - Merge join.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:30:12 - Merge join.0 - 
2021/04/08 11:30:12 - Merge join.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:30:12 - Merge join.0 - 
2021/04/08 11:30:12 - Merge join.0 - (conn=7510) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join.0 - 
2021/04/08 11:30:12 - Merge join.0 - 
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1716)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.steps.mergejoin.MergeJoin.processRow(MergeJoin.java:99)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:30:12 - Merge join.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:30:12 - Merge join.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:30:12 - Merge join.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:30:12 - Merge join.0 - 
2021/04/08 11:30:12 - Merge join.0 - (conn=7510) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join.0 - 
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:30:12 - Merge join.0 - 	... 11 more
2021/04/08 11:30:12 - Merge join.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7510) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:30:12 - Merge join.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:30:12 - Merge join.0 - 	... 13 more
2021/04/08 11:30:12 - Merge join.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:30:12 - Merge join.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:30:12 - Merge join.0 - 	... 16 more
2021/04/08 11:30:12 - Merge join 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Unexpected error
2021/04/08 11:30:12 - Merge join 2.0 - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2021/04/08 11:30:12 - Merge join 2.0 - Unable to get queryfields for SQL: 
2021/04/08 11:30:12 - Merge join 2.0 - SELECT
  *
FROM Cvn_ScientificPublication

2021/04/08 11:30:12 - Merge join 2.0 - 
2021/04/08 11:30:12 - Merge join 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:30:12 - Merge join 2.0 - 
2021/04/08 11:30:12 - Merge join 2.0 - (conn=7509) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join 2.0 - 
2021/04/08 11:30:12 - Merge join 2.0 - 
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:275)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1835)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1769)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1732)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1716)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.mergejoin.MergeJoin.processRow(MergeJoin.java:99)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/04/08 11:30:12 - Merge join 2.0 - 	at java.lang.Thread.run(Unknown Source)
2021/04/08 11:30:12 - Merge join 2.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2021/04/08 11:30:12 - Merge join 2.0 - Couldn't get field info from [SELECT
  *
FROM Cvn_ScientificPublication
]
2021/04/08 11:30:12 - Merge join 2.0 - 
2021/04/08 11:30:12 - Merge join 2.0 - (conn=7509) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join 2.0 - 
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2569)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2416)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:267)
2021/04/08 11:30:12 - Merge join 2.0 - 	... 10 more
2021/04/08 11:30:12 - Merge join 2.0 - Caused by: java.sql.SQLSyntaxErrorException: (conn=7509) Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2550)
2021/04/08 11:30:12 - Merge join 2.0 - 	... 12 more
2021/04/08 11:30:12 - Merge join 2.0 - Caused by: java.sql.SQLException: Table 'etl.Cvn_ScientificPublication' doesn't exist
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
2021/04/08 11:30:12 - Merge join 2.0 - 	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
2021/04/08 11:30:12 - Merge join 2.0 - 	... 15 more
2021/04/08 11:30:14 - 5.4.12_cvn_load_link_publication - ERROR (version 9.1.0.0-324, build 9.1.0.0-324 from 2020-09-07 05.09.05 by buildguy) : Errors detected!
2021/04/08 11:30:14 - control_error - Using run configuration [Pentaho local]
2021/04/08 11:30:14 - control_error - Running transformation using the Kettle execution engine
2021/04/08 11:33:16 - load_link_publication_cvn - Using run configuration [Pentaho local]
2021/04/08 11:33:16 - load_link_publication_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:33:20 - load_link_patente - Using run configuration [Pentaho local]
2021/04/08 11:33:20 - load_link_patente - Running transformation using the Kettle execution engine
2021/04/08 11:33:25 - load_link_patent_cvn - Using run configuration [Pentaho local]
2021/04/08 11:33:25 - load_link_patent_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:33:29 - load_link_articulo - Using run configuration [Pentaho local]
2021/04/08 11:33:29 - load_link_articulo - Running transformation using the Kettle execution engine
2021/04/08 11:33:40 - load_link_libro - Using run configuration [Pentaho local]
2021/04/08 11:33:40 - load_link_libro - Running transformation using the Kettle execution engine
2021/04/08 11:33:45 - load_link_book_cvn - Using run configuration [Pentaho local]
2021/04/08 11:33:45 - load_link_book_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:33:49 - load_link_tesis_externa - Using run configuration [Pentaho local]
2021/04/08 11:33:49 - load_link_tesis_externa - Running transformation using the Kettle execution engine
2021/04/08 11:33:53 - load_link_doctora_thesis_cvn - Using run configuration [Pentaho local]
2021/04/08 11:33:53 - load_link_doctora_thesis_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:33:57 - load_link_tesina_externa - Using run configuration [Pentaho local]
2021/04/08 11:33:57 - load_link_tesina_externa - Running transformation using the Kettle execution engine
2021/04/08 11:36:08 - load_link_accreditation - Using run configuration [Pentaho local]
2021/04/08 11:36:08 - load_link_accreditation - Running transformation using the Kettle execution engine
2021/04/08 11:36:12 - load_link_project - Using run configuration [Pentaho local]
2021/04/08 11:36:12 - load_link_project - Running transformation using the Kettle execution engine
2021/04/08 11:36:17 - load_link_project_cvn - Using run configuration [Pentaho local]
2021/04/08 11:36:17 - load_link_project_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:36:21 - load_link_publication_cvn - Using run configuration [Pentaho local]
2021/04/08 11:36:21 - load_link_publication_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:36:25 - load_link_patente - Using run configuration [Pentaho local]
2021/04/08 11:36:25 - load_link_patente - Running transformation using the Kettle execution engine
2021/04/08 11:36:30 - load_link_patent_cvn - Using run configuration [Pentaho local]
2021/04/08 11:36:30 - load_link_patent_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:36:34 - load_link_articulo - Using run configuration [Pentaho local]
2021/04/08 11:36:34 - load_link_articulo - Running transformation using the Kettle execution engine
2021/04/08 11:36:45 - load_link_libro - Using run configuration [Pentaho local]
2021/04/08 11:36:45 - load_link_libro - Running transformation using the Kettle execution engine
2021/04/08 11:36:49 - load_link_book_cvn - Using run configuration [Pentaho local]
2021/04/08 11:36:49 - load_link_book_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:36:53 - load_link_tesis_externa - Using run configuration [Pentaho local]
2021/04/08 11:36:53 - load_link_tesis_externa - Running transformation using the Kettle execution engine
2021/04/08 11:36:57 - load_link_doctora_thesis_cvn - Using run configuration [Pentaho local]
2021/04/08 11:36:57 - load_link_doctora_thesis_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:37:01 - load_link_tesina_externa - Using run configuration [Pentaho local]
2021/04/08 11:37:01 - load_link_tesina_externa - Running transformation using the Kettle execution engine
2021/04/08 11:37:05 - load_link_dossier - Using run configuration [Pentaho local]
2021/04/08 11:37:05 - load_link_dossier - Running transformation using the Kettle execution engine
2021/04/08 11:37:09 - load_link_research_group - Using run configuration [Pentaho local]
2021/04/08 11:37:09 - load_link_research_group - Running transformation using the Kettle execution engine
2021/04/08 11:37:13 - load_link_university - Using run configuration [Pentaho local]
2021/04/08 11:37:13 - load_link_university - Running transformation using the Kettle execution engine
2021/04/08 11:37:17 - load_link_funding_org_cvn - Using run configuration [Pentaho local]
2021/04/08 11:37:17 - load_link_funding_org_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:37:21 - load_link_person_cvn - Using run configuration [Pentaho local]
2021/04/08 11:37:21 - load_link_person_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:37:25 - load_link_conference - Using run configuration [Pentaho local]
2021/04/08 11:37:25 - load_link_conference - Running transformation using the Kettle execution engine
2021/04/08 11:37:29 - load_link_conference_cvn - Using run configuration [Pentaho local]
2021/04/08 11:37:29 - load_link_conference_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:37:33 - load_link_exhibit - Using run configuration [Pentaho local]
2021/04/08 11:37:33 - load_link_exhibit - Running transformation using the Kettle execution engine
2021/04/08 11:37:37 - load_link_internship - Using run configuration [Pentaho local]
2021/04/08 11:37:37 - load_link_internship - Running transformation using the Kettle execution engine
2021/04/08 11:37:41 - load_link_editor - Using run configuration [Pentaho local]
2021/04/08 11:37:41 - load_link_editor - Running transformation using the Kettle execution engine
2021/04/08 11:37:45 - load_link_member - Using run configuration [Pentaho local]
2021/04/08 11:37:45 - load_link_member - Running transformation using the Kettle execution engine
2021/04/08 11:37:49 - load_link_supervisor - Using run configuration [Pentaho local]
2021/04/08 11:37:49 - load_link_supervisor - Running transformation using the Kettle execution engine
2021/04/08 11:37:53 - load_link_researcher - Using run configuration [Pentaho local]
2021/04/08 11:37:53 - load_link_researcher - Running transformation using the Kettle execution engine
2021/04/08 11:37:57 - load_link_project_contract - Using run configuration [Pentaho local]
2021/04/08 11:37:57 - load_link_project_contract - Running transformation using the Kettle execution engine
2021/04/08 11:38:01 - load_link_employment_contract - Using run configuration [Pentaho local]
2021/04/08 11:38:01 - load_link_employment_contract - Running transformation using the Kettle execution engine
2021/04/08 11:38:05 - load_link_awarded_degree_cvn - Using run configuration [Pentaho local]
2021/04/08 11:38:05 - load_link_awarded_degree_cvn - Running transformation using the Kettle execution engine
2021/04/08 11:38:09 - load_link_funding_program_cvn - Using run configuration [Pentaho local]
2021/04/08 11:38:09 - load_link_funding_program_cvn - Running transformation using the Kettle execution engine
